name: Node.js Package Lisn And Test

on:
  push:
    branches:
      - "*"
      - "!master"

jobs:
  lint-and-test:
    name: Test on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: [10, 12]
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v1
        with:
          version: ${{ matrix.node_version }}
      - run: npm ci
      - run: npm run lint
      - run: npm test
